/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.github.com.juliocesarscheidt.usersmicroservice.UserRate');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.github.com.juliocesarscheidt.usersmicroservice.Rate');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.github.com.juliocesarscheidt.usersmicroservice.UserRate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.repeatedFields_, null);
};
goog.inherits(proto.github.com.juliocesarscheidt.usersmicroservice.UserRate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.displayName = 'proto.github.com.juliocesarscheidt.usersmicroservice.UserRate';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.prototype.toObject = function(opt_includeInstance) {
  return proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.github.com.juliocesarscheidt.usersmicroservice.UserRate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.toObject = function(includeInstance, msg) {
  var f, obj = {
    userUuid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    ratesList: jspb.Message.toObjectList(msg.getRatesList(),
    proto.github.com.juliocesarscheidt.usersmicroservice.Rate.toObject, includeInstance),
    createdAt: jspb.Message.getFieldWithDefault(msg, 3, ""),
    updatedAt: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.github.com.juliocesarscheidt.usersmicroservice.UserRate}
 */
proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.github.com.juliocesarscheidt.usersmicroservice.UserRate;
  return proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.github.com.juliocesarscheidt.usersmicroservice.UserRate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.github.com.juliocesarscheidt.usersmicroservice.UserRate}
 */
proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserUuid(value);
      break;
    case 2:
      var value = new proto.github.com.juliocesarscheidt.usersmicroservice.Rate;
      reader.readMessage(value,proto.github.com.juliocesarscheidt.usersmicroservice.Rate.deserializeBinaryFromReader);
      msg.addRates(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatedAt(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpdatedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.github.com.juliocesarscheidt.usersmicroservice.UserRate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserUuid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRatesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.github.com.juliocesarscheidt.usersmicroservice.Rate.serializeBinaryToWriter
    );
  }
  f = message.getCreatedAt();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getUpdatedAt();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string user_uuid = 1;
 * @return {string}
 */
proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.prototype.getUserUuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.prototype.setUserUuid = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated Rate rates = 2;
 * @return {!Array.<!proto.github.com.juliocesarscheidt.usersmicroservice.Rate>}
 */
proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.prototype.getRatesList = function() {
  return /** @type{!Array.<!proto.github.com.juliocesarscheidt.usersmicroservice.Rate>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.github.com.juliocesarscheidt.usersmicroservice.Rate, 2));
};


/** @param {!Array.<!proto.github.com.juliocesarscheidt.usersmicroservice.Rate>} value */
proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.prototype.setRatesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.github.com.juliocesarscheidt.usersmicroservice.Rate=} opt_value
 * @param {number=} opt_index
 * @return {!proto.github.com.juliocesarscheidt.usersmicroservice.Rate}
 */
proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.prototype.addRates = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.github.com.juliocesarscheidt.usersmicroservice.Rate, opt_index);
};


proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.prototype.clearRatesList = function() {
  this.setRatesList([]);
};


/**
 * optional string created_at = 3;
 * @return {string}
 */
proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.prototype.getCreatedAt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.prototype.setCreatedAt = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string updated_at = 4;
 * @return {string}
 */
proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.prototype.getUpdatedAt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.github.com.juliocesarscheidt.usersmicroservice.UserRate.prototype.setUpdatedAt = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


