name: CI Pipeline

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

env:
  DEPLOYMENT_REPO_NAME: book-recommendations-v2

jobs:
  build:
    name: Setup and Mirror to AWS CodeBuild
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      AWS_REGION: us-east-1
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Lint and test API Gateway
      working-directory: api-gateway/
      run: |
        make build
        make lint-app
        make test-app
    - name: Lint and test Users Microservice
      working-directory: users-microservice/
      run: |
        make build
        make lint-app
        make test-app
    - name: Lint and test Books Microservice
      working-directory: books-microservice/
      run: |
        make build
        make lint-app
        make test-app
    - name: Lint and test Recommendations Microservice
      working-directory: recommendations-microservice/
      run: |
        make build
        make lint-app
        make test-app
    - name: Build and push Docker images
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      working-directory: infrastructure/terraform/
      run: |
        IMAGE_VERSION=$(git rev-parse --short=7 HEAD) make push-image
    - name: Retrieve private SSH file to Git Authentication through SSH
      if: ${{ github.event_name != 'pull_request' }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/book-recommendations/book-recommendations /tmp/book-recommendations
        chmod 600 /tmp/book-recommendations
    - name: Set SSH config file
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        ssh-keyscan -t rsa git-codecommit.${AWS_REGION}.amazonaws.com >> ~/.ssh/known_hosts
        echo "Host git-codecommit.*.amazonaws.com" >> ~/.ssh/config
        echo "User ${{ secrets.CODE_COMMIT_SSH_KEY_ID }}" >> ~/.ssh/config
        echo "IdentityFile /tmp/book-recommendations" >> ~/.ssh/config
        chmod 600 ~/.ssh/config
    - name: Mirror to AWS CodeCommit
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        git remote add codecommit ssh://git-codecommit.${AWS_REGION}.amazonaws.com/v1/repos/${DEPLOYMENT_REPO_NAME}
        git remote update codecommit
        git fetch --unshallow codecommit || true
        git push -f codecommit $GITHUB_REF_NAME
        # git push --mirror ssh://git-codecommit.${AWS_REGION}.amazonaws.com/v1/repos/${DEPLOYMENT_REPO_NAME}
    - name: Remove temp files
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        rm -rf ~/.ssh/config /tmp/book-recommendations
    - name: Print job status
      run: |
        echo "JOB STATUS ${{ job.status }}"

  notify:
    name: Notify Pipeline
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    if: ${{ github.event_name == 'pull_request' }}
    needs: build
    env:
      BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
      PULL_REQUEST_NUMBER: ${{ github.event.number }}
      OWNER: juliocesarscheidt
    steps:
    - name: The job has failed
      if: ${{ failure() }}
      run: |
        docker container run -i --rm \
          --env GITHUB_TOKEN=$BOT_GITHUB_TOKEN \
          --env GITHUB_OWNER=$OWNER \
          --env GITHUB_REPO=$DEPLOYMENT_REPO_NAME \
          --env GITHUB_COMMENT_TYPE=pr \
          --env GITHUB_PR_ISSUE_NUMBER=$PULL_REQUEST_NUMBER \
          --env GITHUB_COMMENT_FORMAT="<b>Comment</b><br/>{{.}}" \
          --env GITHUB_COMMENT="The build of commit $GITHUB_SHA has failed" \
          cloudposse/github-commenter:latest
    - name: The job has succeeded
      if: ${{ success() }}
      run: |
        docker container run -i --rm \
          --env GITHUB_TOKEN=$BOT_GITHUB_TOKEN \
          --env GITHUB_OWNER=$OWNER \
          --env GITHUB_REPO=$DEPLOYMENT_REPO_NAME \
          --env GITHUB_COMMENT_TYPE=pr \
          --env GITHUB_PR_ISSUE_NUMBER=$PULL_REQUEST_NUMBER \
          --env GITHUB_COMMENT_FORMAT="<b>Comment</b><br/>{{.}}" \
          --env GITHUB_COMMENT="The build of commit $GITHUB_SHA was successful, LGTM" \
          cloudposse/github-commenter:latest
