name: CI Pipeline PR

on:
  pull_request:
    branches: [ main, development ]

env:
  REPOSITORY_NAME: book-recommendations-v2

jobs:
  build:
    name: Setup and Mirror to AWS CodeBuild
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      AWS_REGION: us-east-1
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Lint and Unit Tests for API Gateway
      working-directory: api-gateway/
      run: |
        make build
        make lint-app
        make test-app
    - name: Lint and Unit Tests for Users Microservice
      working-directory: users-microservice/
      run: |
        make build
        make lint-app
        make test-app
    - name: Lint and Unit Tests for Books Microservice
      working-directory: books-microservice/
      run: |
        make build
        make lint-app
        make test-app
    - name: Lint and Unit Tests for Recommendations Microservice
      working-directory: recommendations-microservice/
      run: |
        make build
        make lint-app
        make test-app
    - name: Print job status
      run: |
        echo "JOB STATUS ${{ job.status }}"

  notify:
    name: Notify Pipeline
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    needs: build
    env:
      BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
      PULL_REQUEST_NUMBER: ${{ github.event.number }}
      OWNER: juliocesarscheidt
    steps:
    - name: The job has failed
      if: ${{ failure() }}
      run: |
        docker container run -i --rm \
          --env GITHUB_TOKEN=$BOT_GITHUB_TOKEN \
          --env GITHUB_OWNER=$OWNER \
          --env GITHUB_REPO=$REPOSITORY_NAME \
          --env GITHUB_COMMENT_TYPE=pr \
          --env GITHUB_PR_ISSUE_NUMBER=$PULL_REQUEST_NUMBER \
          --env GITHUB_COMMENT_FORMAT="<b>Comment</b><br/>{{.}}" \
          --env GITHUB_COMMENT="The build of commit $GITHUB_SHA has failed" \
          cloudposse/github-commenter:latest
    - name: The job has succeeded
      if: ${{ success() }}
      run: |
        docker container run -i --rm \
          --env GITHUB_TOKEN=$BOT_GITHUB_TOKEN \
          --env GITHUB_OWNER=$OWNER \
          --env GITHUB_REPO=$REPOSITORY_NAME \
          --env GITHUB_COMMENT_TYPE=pr \
          --env GITHUB_PR_ISSUE_NUMBER=$PULL_REQUEST_NUMBER \
          --env GITHUB_COMMENT_FORMAT="<b>Comment</b><br/>{{.}}" \
          --env GITHUB_COMMENT="The build of commit $GITHUB_SHA was successful, LGTM" \
          cloudposse/github-commenter:latest
